version: '3.3'
services:
  db:
    container_name: db
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_dev
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
#      - ./create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh

  app:
    container_name: app
    image: app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/lera/PycharmProjects/TestProject_02/fastapi_app:/code"
#      - ./:/src
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db

volumes:
  postgresql:
    driver: local