version: '3.3'
services:
  db:
    container_name: ${DB_HOST}
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgresql:/var/lib/postgresql/data

  app:
    container_name: app
    image: app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/code"
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db

volumes:
  postgresql:
    driver: local
